# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true
  pull:
    cmds:
      - git reset --hard
      - git pull
  build:
    desc: build da shiut
    cmds:
      - task: pull
      - make setup
      - make build
  start:
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user start {{.PROJECT}}
  stop:
    cmds:
      - ssh $REMOTE_HOST 'source ~/.zshrc;systemctl --user stop {{.PROJECT}}
  deploy:
    desc: deploy
    cmds:
      - task: stop
      - ssh $REMOTE_HOST 'source ~/.zshrc;cd ~/src/{{.PROJECT}};task build;cp navidrome /store/navidrome/bin
      - task: start
