# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true
  pull:
    cmds:
      - git reset --hard
      - git pull
  build:
    desc: build da shiut
    cmds:
      - NODE_OPTIONS=--max-old-space-size=8192 make buildall
